image: barichello/godot-ci:4.2.1

variables:
  EXPORT_NAME: blank

stages:
  - export
  - deploy


linux:
  stage: export
  script:
    - mkdir -v -p build/linux
    - godot -v --export-release "Linux/X11" ./build/linux/$EXPORT_NAME.x86_64
  artifacts:
    name: $EXPORT_NAME-$CI_JOB_NAME
    paths:
      - build/linux

