image: barichello/godot-ci:4.2.1

variables:
  EXPORT_NAME: blank

stages:
  - export
  - deploy

windows:
  stage: export
  script:
    - mkdir -v -p build/windows
    - godot -v --export "Windows Desktop" ./build/windows/$EXPORT_NAME.exe
  artifacts:
    name: $EXPORT_NAME-$CI_JOB_NAME
    paths:
      - build/windows
