image: barichello/godot-ci:4.2.2

variables:
  EXPORT_NAME: blank

stages:
  - export
  - deploy

linux:
  stage: export
  script:
    - mkdir -v -p build/linux
    # Use OpenGL 3 rendering driver for exporting
    - godot -v --rendering-driver opengl3 --export-release "Linux/X11" ./build/linux/$EXPORT_NAME.x86_64
  artifacts:
    name: $EXPORT_NAME-$CI_JOB_NAME
    paths:
      - build/linux


