image: mariamossama/blank-godot-image:latest

variables:
  EXPORT_NAME: blank

stages:
  - export
  - deploy

linux:
  stage: export
  script:
    - mkdir -v -p build/linux
    # Use xvfb-run to simulate an X server with the OpenGL 3 rendering driver
    - xvfb-run -s "-screen 0 1024x768x24" godot -v --rendering-driver opengl3 --export-release "Linux/X11" ./build/linux/$EXPORT_NAME.x86_64
  artifacts:
    name: $EXPORT_NAME-$CI_JOB_NAME
    paths:
      - build/linux



