image: mariamossama/blank-godot-image:latest

cache:
  key: import-assets
  paths:
    - .godot/imported/


variables:
  EXPORT_NAME: blank
  ITCHIO_USERNAME: blank_bomberman
  ITCHIO_GAME: blank_dyna-blasterGame

stages:
  - import-assets
  - export
  - deploy

import-assets:
  stage: import-assets
  script:
    - godot --headless --verbose --editor --quit

windows:
  stage: export
  script:
    - mkdir -v -p build/windows
    - xvfb-run -s "-screen 0 1024x768x24" godot -v --rendering-driver opengl3 --export-release "Windows Desktop" ./build/windows/$EXPORT_NAME.exe
  artifacts:
    name: $EXPORT_NAME-$CI_JOB_NAME
    paths:
      - build/windows

linux:
  stage: export
  script:
    - mkdir -v -p build/linux
    # Use xvfb-run to simulate an X server with the OpenGL 3 rendering driver
    - xvfb-run -s "-screen 0 1024x768x24" godot -v --rendering-driver opengl3 --export-release "Linux/X11" ./build/linux/$EXPORT_NAME.x86_64
  artifacts:
    name: $EXPORT_NAME-$CI_JOB_NAME
    paths:
      - build/linux

# Itch.io Deploy
itchio:linux:
  stage: deploy
  script:
    - butler push ./build/linux $ITCHIO_USERNAME/$ITCHIO_GAME:linux
  dependencies:
    - linux

itchio:windows:
  stage: deploy
  script:
    - butler push ./build/windows $ITCHIO_USERNAME/$ITCHIO_GAME:windows
  dependencies:
    - windows